import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import styled from 'styled-components';
import AeropayDropdown from '../components/AeropayDropdown';
import { Box } from '../components/basecomponents/Box';
import { getProducts } from '../components/common/getProducts';
import ProductsList from '../components/ProductsList';
import { useUserContext } from '../context/UserContext';

export const getStaticProps = async () => {
  const products = await getProducts();
  
  return {
    props: {
      products,
    }
  }
}

const Main = styled(Box)`
  width: 100%;
`;
export default function Home({ products }) {
  return (
    <div >
      <Head>
        <title>Tech Zone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Main as="main">
        <Box
          maxWidth={1464}
        >
          <section>
            <Box
              as="header"
              display="flex"
              justifyContent="end"
            >
              <AeropayDropdown></AeropayDropdown>        
            </Box>
            <ProductsList products={products}></ProductsList>
          </section>
        </Box>
       </Main>

    </div>
  )
}
