import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import styled from 'styled-components';
import AeropayDropdown from '../components/AeropayDropdown';
import { Box } from '../components/basecomponents/Box';
import { getProducts } from '../components/common/getProducts';
import ProductsList from '../components/ProductsList';
import { getUser } from '../components/common/getUser';
import { useUserContext } from '../context/UserContext';
import { useProductsContext } from '../context/ProductsContext';

export const getStaticProps = async () => {
  const user = await getUser();
  const products = await getProducts();
  const productsSSR = products;
  const categories = productsSSR.map(product => product.category);
  const categoriesSSR = [... new Set(categories)];
 
  return {
    props: {
      productsSSR,
      categoriesSSR,
      user,
    }
  }
}

const Main = styled(Box)`
  width: 100%;
`;
export default function Home({ user, productsSSR, categoriesSSR }) {
  const { points, setPoints, setName } = useUserContext();
  const { categories, setCategories, products, setProducts } = useProductsContext();
  useEffect(() => {
    setPoints(user.points);
    setProducts(productsSSR);
    setName(user.name);
    setCategories(categoriesSSR);  

  }, []);
  
  return (
    <div >
      <Head>
        <title>Tech Zone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Main as="main">
        <Box
          maxWidth={1464}
        >
          <section>
            <Box
              as="header"
              display="flex"
              justifyContent="end"
            >
              {user && <AeropayDropdown></AeropayDropdown>}
            </Box>
            {products && <ProductsList></ProductsList>}
          </section>
        </Box>
       </Main>
    </div>
  )
}
