import Head from 'next/head'
import { useState } from 'react';
import styled from 'styled-components'

export default function Home() {
  const Parrafito = styled.p`
    background: ${props => props.theme.brand.default};
  `
  return (
    <div >
      <Head>
        <title>Tech Zone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <Parrafito>CAMBIO DE COLOR</Parrafito>
        <p>HOLIS</p>
      </main>

    </div>
  )
}
